version: "3.3"
services:

  db:
    image: postgres:9.6.21-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./code:/app:delegated
    ports:
      - "3000:3000"
    depends_on:
      - db
